BEGIN
Insert into replenishment_task (ID,CODE,INTERNAL_CODE,PRIORITY,QUANTITY,EFFECTIVE_QUANTITY,END_DATE,START_DATE,STATUS,USERNAME,WAREHOUSE_CODE,TRACEABLE,TYPE,DELETED,INSTANCE_KEY,REFERENCE_CODE,CURRENT_STATE,COMPANY,CREATION_DATE,SUB_TYPE,VERSION,LAST_UPDATE_DATE) 
values (replenishment_task_seq.nextval,'ALFOTEST','000000000000421023',null,'200',null,null,null,'Open','john','3702','1','Automatic Generation',null,null,null,null,null,to_timestamp('30-GIU-16 22:20:20,886000000','DD-MON-RR HH24:MI:SSXFF'),null,'8',to_timestamp('30-GIU-16 22:28:11,696000000','DD-MON-RR HH24:MI:SSXFF'));
Insert into REPLENISHMENT_LOCATION_LNK (ID,SOURCE_LOCATION,PROPOSED_SEQUENCE,TARGET_LOCATION,DELETED,ID_REPLENISHMENT_TASK,TARGET_PRIORITY) 
values (REPLENISHMENT_LOCATION_LNK_SEQ.nextval,'GR0001',null,'GS0005',null,(select ID from REPLENISHMENT_TASK where code='ALFOTEST'),null);
Insert into REPLENISHMENT_LOCATION_LNK (ID,SOURCE_LOCATION,PROPOSED_SEQUENCE,TARGET_LOCATION,DELETED,ID_REPLENISHMENT_TASK,TARGET_PRIORITY) 
values (REPLENISHMENT_LOCATION_LNK_SEQ.nextval,'GR0002',null,'GS0005',null,(select ID from REPLENISHMENT_TASK where code='ALFOTEST'),null);
Insert into REPLENISHMENT_LOCATION_LNK (ID,SOURCE_LOCATION,PROPOSED_SEQUENCE,TARGET_LOCATION,DELETED,ID_REPLENISHMENT_TASK,TARGET_PRIORITY) 
values (REPLENISHMENT_LOCATION_LNK_SEQ.nextval,'GR0001',null,'GS0005',null,(select ID from REPLENISHMENT_TASK where code='ALFOTEST'),null);
COMMIT;
END;