BEGIN
Insert into REPLENISHMENT_TASK (ID,CODE,INTERNAL_CODE,PRIORITY,QUANTITY,EFFECTIVE_QUANTITY,END_DATE,START_DATE,STATUS,USERNAME,WAREHOUSE_CODE,TRACEABLE,TYPE,DELETED,INSTANCE_KEY,REFERENCE_CODE,CURRENT_STATE,COMPANY,CREATION_DATE,SUB_TYPE,VERSION,LAST_UPDATE_DATE) 
values (REPLENISHMENT_TASK_SEQ.nextval,'${code}','000000000010002098',null,'175',null,null,null,'Open',null,'3701','1','Automatic Generation',null,null,null,null,null,to_timestamp('06/07/2017 12:20:21','MM/DD/YYYY HH24:MI:SS'),null,'2',to_timestamp('06/26/2017 08:00:21','MM/DD/YYYY HH24:MI:SS'));
Insert into REPLENISHMENT_LOCATION_LNK (ID,SOURCE_LOCATION,PROPOSED_SEQUENCE,TARGET_LOCATION,DELETED,ID_REPLENISHMENT_TASK,TARGET_PRIORITY)                            
values (REPLENISHMENT_LOCATION_LNK_SEQ.nextval,'P078L20',null,'B186Z91',null,(select id from REPLENISHMENT_TASK where code='${code}'),null);
COMMIT;
END;