egin
Insert into REPLENISHMENT_TASK (ID,CODE,INTERNAL_CODE,PRIORITY,QUANTITY,EFFECTIVE_QUANTITY,END_DATE,START_DATE,STATUS,USERNAME,WAREHOUSE_CODE,TRACEABLE,TYPE,DELETED,INSTANCE_KEY,REFERENCE_CODE,CURRENT_STATE,COMPANY,CREATION_DATE,SUB_TYPE,VERSION,LAST_UPDATE_DATE) 
values (REPLENISHMENT_TASK_SEQ.nextval,'${code}','000000000000000001',null,'9999',null,null,null,'Started','john','3702','1','Automatic Generation',null,null,null,null,null,to_timestamp('09/01/2016 08:00:02','MM/DD/YYYY HH24:MI:SS'),null,'1',to_timestamp('09/01/2016 08:08:14','MM/DD/YYYY HH24:MI:SS'));
Insert into REPLENISHMENT_LOCATION_LNK (ID,SOURCE_LOCATION,PROPOSED_SEQUENCE,TARGET_LOCATION,DELETED,ID_REPLENISHMENT_TASK,TARGET_PRIORITY)                                 
values (REPLENISHMENT_LOCATION_LNK_SEQ.nextval,'QN0010',null,'QN0011',null,(select ID from REPLENISHMENT_TASK where code='${code}'),null);
commit;
End;