def clusterIP = "whatever"
pipeline {
    //parameters {
    //    string(name: 'clusterIP', defaultValue: 'localhost', description: 'Cluster IP that is under test')
    //}
    agent {
        docker {
            image 'maven:3-jdk-11-slim'
            args '-v maven-home:/root/.m2 -e NEXUS_HOST=${NEXUS_HOST}'
        }
    }
    stages {
        stage('Run E2E tests') {
            steps {
                // TODO cluster.ip arg isn't propagated to tests, so implement propogation.
                echo "Run tests against cluster IP ${clusterIP}"
                sh 'mvn clean test -Dcluster.ip=${clusterIP}'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}